### PR TITLE
Added shell script (bash) to automate the process of using Forge Networking from sources

### PR DESCRIPTION
**Pull request by andgeno**
As the title says, a script to automate the process. It's written for bash. So Windows users will need to have this installed (Git for Windows, Cygwin, ...). I've only tested it on Windows but I think it should work on macOS and Linux as well.

### CODE REVIEW

**Comment by andgeno** [comment]
This is how it looks like when the script is run:

screenshot

**Comment by andgeno** [comment]
My name on the FN Discord is: geno

**Comment by andgeno** [comment]
Maybe we should move the script into a `bin`, `tools`, or `scripts` folder? Just let me know and I'll move it ;-)

**Comment by NFMynster** [comment]
Neat, you should make a wiki page about it. I'll make a community section soon. @andgeno

**Pull request merged**
