### PR TITLE
Fixed Master Server

### PR DESCRIPTION
**Pull request by Tech305**
The connection between the different projects  where not loading correctly so now everything should work. also i added a dll i created called stitch it just makes it easy to get your machine ipaddress insted of having the user type it in it also has a default port but you don't have to use that port you can promt for the port like normal.

### CODE REVIEW

**Comment by baflink** [comment]
Can you reset any of the files that are auto generated like the .txt, .sqlite, .xml, files and so forth. Just so I know exactly what was manually updated?

**Comment by phalasz** [comment]
Is this PR still relevant or can it be closed? It's been open for more then a year.

**Comment by phalasz** [comment]
Is this still relevant? The PR has been open for a really long time with a lot of changes going in since. Can this be closed without merging?

**Comment by NFMynster** [comment]
Yeah bumped it as well. Open if desired @Tech305

**Pull request closed without merging**
