### PR TITLE
NCW Improvements to Validation and Logging

### PR DESCRIPTION
**Pull request by WhelanB**
Expands validation of fields to the NCW when the user clicks "Save & Compile"

Currently, the NCW populates fields for a given object by using Reflection to retrieve the fields in the class, and performs some filtering based on the name of the field, leaving only the private variables produced by the NCW. This led to issues similar to that described in #152 where fields containing the words "Changed" and "Interpolation" would be produced in the generated code, but on reopening the NCW, these fields would be treated as Changed events or Interpolation variables and be excluded, giving the impression of vanishing variables with no information relayed back to the user as to why this issue was occurring.

This PR modifies this logic to instead have the NCW retrieve fields based on a new attribute, [ForgeGeneratedField], which indicates this field was generated by the NCW, rather than relying on string comparisons. When the user presses the "Save & Compile" button in the NCW to invoke compilation, the previous "isSetupCorrectly" method (now "ValidateSetup") performs validation on the fields/RPCs as it did previously, but now also ensures that no conflict will occur between fields ending in "Changed" or "Interpolation" and the respective auto-generated events and variables. 

The existing validation has also been expanded on to provide more verbose error messages, and the method now returns an object of type ValidationResult which contains a boolean value indicating success or failure to validate, alongside a list of errors which occurred in validation. Previously, the validation step would terminate as soon as a single issue was encountered, but instead the ValidationResult contains all discovered issues, and these are logged to the console on failure.

The isValidName method was also changed, as the Regex expression it matched against was not valid for all cases. It now relies on CodeDomCompiler to validate the identifier is valid.

The new addition of [ForgeGeneratedField] in the NetworkObject template does not affect users, as the original method of finding fields has been preserved for cases where no ForgeGeneratedField attributed fields are found. Combined with the new NetworkObject template, this provides a natural update process on the next compile.

### CODE REVIEW

**Comment by phalasz** [comment]
Like where this PR is going. Still need to give it a whirl at some point.

Also I'm a fan of automation and not trusting the user to make upgrade changes. How hard would it be to add an automatic update to existing generated classes? Even if it is as simple as clicking a button to update them all?

**Comment by WhelanB** [comment]
> Like where this PR is going. Still need to give it a whirl at some point.
> 
> Also I'm a fan of automation and not trusting the user to make upgrade changes. How hard would it be to add an automatic update to existing generated classes? Even if it is as simple as clicking a button to update them all?

I've updated the description to reflect the newer commit changes better. In theory, the actual upgrade step itself wouldn't be too difficult, as the only change involves adding the [ForgeGeneratedField] above the private fields produced by the NCW, however it would potentially require Forge to be able to parse both without the attribute and with. It would probably work best as a batch update that would perform the upgrade across all objects.

My initial reasoning for using an attribute was to allow it to later be applied to RPCs to fix the same naming issue from occurring, but it's not ideal in requiring classes to be updated - It may be possible to instead populate NCW fields via a combination of the private field and public property representing each field, and the RPCs via their ParameterInfo, I'll have a look into this and see if it is feasible as an alternative solution

**Comment by WhelanB** [comment]
> Like where this PR is going. Still need to give it a whirl at some point.
> 
> Also I'm a fan of automation and not trusting the user to make upgrade changes. How hard would it be to add an automatic update to existing generated classes? Even if it is as simple as clicking a button to update them all?

Thanks! I've updated the description to hopefully reflect the newer commit changes better. 

In theory, the actual upgrade step itself wouldn't be too difficult, as the only change involves adding the [ForgeGeneratedField] above the private fields produced by the NCW, however it would potentially require Forge to be able to parse both without the attribute and with. It would probably work best as a batch update that would perform the upgrade across all objects.

My initial reasoning for using an attribute was to allow it to also apply to RPCs, but it's not ideal in requiring classes to be updated - It may be possible to instead populate NCW fields via a combination of the private field and public property representing each field. I'll have a look into this and see if it is feasible instead, as it will save users from having to go through the update process!

**Comment by phalasz** [comment]
I agree with the batch upgrade, it should be done on all objects at the same time.

**Comment by WhelanB** [comment]
I think trying to parse based on private/public property matching will end up being too fragile, so I've gone ahead and added an update process to the NCW. Basically, it first tries to find [ForgeGeneratedFields], and if none are found, makes an attempt at finding the fields via the old process of elimination. When the user recompiles, the [ForgeGeneratedField] attribute will be added as part of the regeneration process. I also threw in a fix for #152 as there doesn't seem to be any particular issue with having "Changed" at the end of an RPC identifier.

**Pull request merged**
