### PR TITLE
Multiple small fixes (see comments)

### PR DESCRIPTION
**Pull request by bfishman**
Contains three (unrelated) commits - 

https://github.com/BeardedManStudios/ForgeNetworkingRemastered/commit/17c1374c9f4257037eb433b504ccd49bdc546563   adds a null check to the server in MultiplayerMenu.cs.  Without this, launching then closing the game without attempting to connect to a server would cause a null reference exception.

https://github.com/BeardedManStudios/ForgeNetworkingRemastered/commit/089798c396c72dbed99537a1380c8c6478a95e5c  incorporates some preprocessing directives from @NFMynster needed for debug builds (i.e. running Forge from source). 

https://github.com/BeardedManStudios/ForgeNetworkingRemastered/pull/147/commits/17700ce56185d84391f727db52db3076d9ffde07  removes the default IP address from the NAT Punch host field in MultiplayerMenu's canvas script.  This was causing the client application to crash when closed -- see issue #139 .  @NFMynster found that this was likely related to issue #136 (which remains open)

### CODE REVIEW

**Comment by NFMynster** [comment]
+1!

**Comment by bfishman** [comment]
https://github.com/BeardedManStudios/ForgeNetworkingRemastered/pull/147/commits/17700ce56185d84391f727db52db3076d9ffde07  removes the default IP address from the NAT Punch host field in MultiplayerMenu's canvas script.  This was causing the client application to crash when closed -- see issue #139 .  @NFMynster found that this was likely related to issue #136 (which remains open)

**Comment by bfishman** [comment]
Closed this because there's an issue with the generated plugin dll

Will resubmit shortly

**Comment by bfishman** [comment]
Resubmitting as two separate PRs.

**Pull request closed without merging**
