### PR TITLE
Feature/latency simulation

### PR DESCRIPTION
**Pull request by Snordia**

### CODE REVIEW

**Comment by Snordia** [comment]
When browsing through the code I found that the LatencySimulation value was never used within the code of Forge, that's why I implemented it myself. Internally we've been able to use this for testing high-latency cases.

**Comment by BrentFarris** [comment]
I have merged a big cleanup branch and so you will probably need to merge current develop into your fork and resolve conflicts, sorry about this. The main breaking change in develop is the folder paths have updated their names to not have spaces. Please see [this commit](https://github.com/BeardedManStudios/ForgeNetworkingRemastered/pull/292) for more info on the changes

**Comment by NFMynster** [comment]
@BrentFarris The current latency simulation code is non existing, there's only references to it. I'm guessing it didn't get ported over from Forge Classic.
Is this implementation similar and could you approve?
@Snordia Could you update the pull request to resolve the conflicts?

**Comment by Snordia** [comment]
Unfortunately I'm not working with Forge anymore, if anyone wants to still fix this feel free take over my fork. Closing this PR for now.

**Pull request closed without merging**
