### PR TITLE
Added Unity assembly definitions

### PR DESCRIPTION
**Pull request by JasperCiti**
For more info why it is useful see https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

Discord username: @JasperCiti#0405

### CODE REVIEW

**Comment by phalasz** [comment]
The main issue with asmdefs is that Forge uses a lot of partial classes. So in case someone wants to add a new partial class to add more functionality to one of the Forge classes then they will have to add the file into the forge directory as those files will need to be compiled into the same assembly.

**Comment by JasperCiti** [comment]
That's too bad. I have try to move the generated stuff outside the assembly, but then the Chat module break. Will have to refactor the Chat module first or something...

**Comment by phalasz** [comment]
It's not just the generated folder though, but any other partial class. As the other part of some of the generated folder's partial classes are in the main source files in `Scripts/Networking`.

**Comment by JasperCiti** [comment]
But if you have code inside one of your own assemblies that depend on FNR, how to you reference that?

**Comment by phalasz** [comment]
You can reference them by adding FNR as a dependency to your assembly. The main issue is if you want to add further functionality to a partial class, as that would need to be done in the FNR directories so it gets added to the FNR assembly.

c# docs:
```
All partial-type definitions meant to be parts of the same type must be defined in the same assembly and the same module (.exe or .dll file). Partial definitions cannot span multiple modules.
```

**Comment by phalasz** [comment]
One option could be is to move `Assets/Bearded Man Studios Inc/ForgeNetworkingRemaster.asmdef` into `Assets/Bearded Man Studios Inc/Scripts/Networking/` as that folder should not have any partial classes and used to be compiled into a dll in the past.

**Comment by BrentFarris** [comment]
I have merged a big cleanup branch and so you will probably need to merge current develop into your fork and resolve conflicts, sorry about this. The main breaking change in develop is the folder paths have updated their names to not have spaces. Please see [this commit](https://github.com/BeardedManStudios/ForgeNetworkingRemastered/pull/292) for more info on the changes

**Comment by phalasz** [comment]
Closing this as there have been no movement on it for a long time.

**Pull request closed without merging**
