### PR TITLE
Optimization of multiple objects serialization

### PR DESCRIPTION
**Pull request by kamyker**
Instead of mapping/appending every object to a BMSByte (which causes a lot of Resize calls):
1. All of them are converted to byte[] using GetBytesArray
2. Then they are stored in byte[][]
3. Then whole byte[][] is appended to BMSByte which resize only once
+-20% faster depending how much objects are added at once

### CODE REVIEW

**Comment by baflink** [comment]
Jagged arrays are expensive in general and I tend to try to avoid them when I can. I'm interested in testing the other changes though. I'm assuming that this is the PR update that you were mentioning in the other PR so can you do the PR to develop instead of master so I can test it out?

**Comment by kamyker** [comment]
Oh I can just edit PR thought I have to make new one :D. Just try for yourself, run that changed TestObjectMapper before and after PR changes. It's much faster, especially when writing big arrays to BMSByte (even twice faster). Was trying also with MemoryStream instead of jagged arrays and it was slower (i guess due to resizing... oh wait now I have next idea: maybe memoryStream with fixed size would be the fastest! 🗡 ).

**Comment by kamyker** [comment]
MemoryStream seems to be only few % faster but would also require to make additional ways to get string size. 
Also tried to count lenght of all objects, resize BMSByte at start once then blockCopy every object converted to byte[] directly to BMSByte aaand it was little bit slower.

**Comment by baflink** [comment]
Thanks! Will check it out asap :)

**Pull request merged**
