### PR TITLE
Fixed wrong NetworkBehavior Components order cause Network Instantiation error

### PR DESCRIPTION
**Pull request by StellarYan**
Prefab used to have to put the  Instantiation NetworkBehviour  Above other NetworkBehviours it, otherwise cause error.
Now, the order of NetworkBehviour doesn't matter.

### CODE REVIEW

**Comment by NFMynster** [comment]
Hello @StellarYan 
What's your github username? 
Wondering if your PR essentially does the same as this one? https://github.com/BeardedManStudios/ForgeNetworkingRemastered/pull/177

**Comment by StellarYan** [comment]
My github username? @StellarYan, you already say it.

No, that's different. My PR has nothing to do with nested objects, but try to solve instantiation error of single object.

**Comment by NFMynster** [comment]
Ah, haha, my mistake, meant your Discord name!
If you even are on the Discord?

**Comment by StellarYan** [comment]
I am on Discord now.My Discord name is @stellary

**Pull request merged**
